Fix: MongoDB promisify error
The error "TypeError: (0 , util_1.promisify) is not a function" is caused by an incompatibility with the MongoDB library. This commit addresses the issue.